# Generated by Django 4.1 on 2023-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Account_Name',
            new_name='account_Name',
        ),
        migrations.RenameField(
            model_name='customer_account_details',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='customer_account_details',
            old_name='Account_Number',
            new_name='account_Number',
        ),
        migrations.RenameField(
            model_name='customer_account_details',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='account',
            name='account_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
